### PR TITLE
Misc `css` fixes. Closes #265

### LINKED ISSUE #265: Unnecessary Overflow in TagSelectorWidget
image

### PR DESCRIPTION
**Pull request by umesh-timalsina**
Creates a `scm-r6o-widget` class to apply common styles to the annotation editor.

### CODE REVIEW

File: js/circuit-annotator/src/Components/OpenSeadragon/DetectionSensitivityWidget.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ export default function DetectionSensitivityWidgetFactory(annotationFilter) {
         const isPort = !isNewAnnotation && !!args.annotation.underlying.parent_id;
 
         const container = document.createElement('div');
-        container.className = 'detection-sensitivity-widget';
+        container.className = 'detection-sensitivity-widget scm-r6o-widget';
```
Comment (brollb) [inline js/circuit-annotator/src/Components/OpenSeadragon/DetectionSensitivityWidget.js:19]: What does the r6o segment mean?

Comment (umesh-timalsina) [reply js/circuit-annotator/src/Components/OpenSeadragon/DetectionSensitivityWidget.js:19]: I think this is referring to [`regocito`](https://github.com/recogito), the umbrella organization for [`annotoroious`](https://github.com/recogito/annotorious-openseadragon).

Comment (umesh-timalsina) [reply js/circuit-annotator/src/Components/OpenSeadragon/DetectionSensitivityWidget.js]: Changed the classname,.
